import React from 'react';

export default props => (
    <div>
        <h1 className="text-center">Secret Documents</h1>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem, sit excepturi alias tempora aliquam nesciunt numquam asperiores expedita rem laborum porro enim dignissimos error est corrupti accusantium minus a odio modi ipsum quos laboriosam incidunt? Fugiat earum labore ducimus iste saepe ipsa, beatae praesentium culpa minima delectus impedit voluptatibus aut sed architecto autem explicabo voluptatem quibusdam, dignissimos deserunt tempore nostrum. Earum quasi corporis deleniti, fuga at ipsa facere cum excepturi fugit consectetur impedit architecto ad ipsum suscipit illo eos hic, maxime, dicta officia nemo nam ab vero similique. Id harum doloremque amet. Quos nostrum sed vel minus pariatur architecto, cupiditate assumenda id optio perferendis tempore neque et fugit officia fugiat maxime dolor ullam saepe. Aperiam dolorem eum magnam error voluptatem, ducimus sit quos facilis minus voluptates, nobis nihil. Cum, excepturi. Harum error dignissimos ipsam libero dolor aut nemo ad accusantium nulla, expedita reprehenderit alias. Veniam, consectetur dignissimos. Omnis, provident. Aliquid laboriosam architecto ullam quam dolores recusandae. Laudantium earum soluta totam ad quibusdam saepe cumque esse nobis unde non. Cum quae commodi sunt velit, tempora, ullam voluptates quo iure pariatur deserunt natus impedit qui accusamus exercitationem. Necessitatibus minima, odio quisquam ut tenetur sed fugit eveniet, odit unde, velit cum tempore dolore!</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolore rem in vero, laudantium sunt porro atque illo nemo soluta accusantium repellendus reiciendis quidem dolorum est ad distinctio, sint odit quasi ipsam sit. Deserunt labore omnis ad exercitationem blanditiis, molestias laboriosam laudantium hic minima veritatis commodi asperiores maiores quasi minus quisquam?
        Corrupti hic, facere ipsam fugit laborum sapiente odio rem aspernatur. Exercitationem totam asperiores esse fugit? Beatae iure quas modi quos ullam expedita reprehenderit doloribus quasi fugiat porro ipsum nulla ea cupiditate minus doloremque ratione odio harum incidunt id quam, velit, corporis eveniet obcaecati numquam! Possimus vel labore illum magnam fuga.
        Excepturi similique animi repellendus esse neque, sed incidunt minima, soluta repellat ex voluptate blanditiis eveniet rem obcaecati unde dignissimos veniam! Animi porro accusamus non ut nihil sunt eius obcaecati pariatur voluptatibus laboriosam doloremque repellat ipsum temporibus blanditiis, iure sed, nemo dolor beatae explicabo excepturi minima consequuntur! Beatae saepe eveniet aspernatur.
        Rerum quae autem dolore! Provident laudantium recusandae deserunt odit nam eos saepe nesciunt harum! Aliquid corporis cupiditate id quisquam dicta numquam nihil harum nulla odit? Labore assumenda totam sit mollitia expedita quidem aliquam eos aperiam. Optio, perferendis eius quasi provident earum iste, ab temporibus quis quos aliquam sint maiores sequi.</p>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis distinctio harum ut aut repellat obcaecati consequatur nobis quod ipsum facere!</p>
        <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Maxime tempore natus doloribus corrupti quo eaque placeat illo quidem ut cum. Architecto excepturi quisquam deserunt saepe dolore sunt voluptatibus laudantium doloremque a cumque totam facere, amet recusandae esse placeat molestias perspiciatis veritatis voluptatem assumenda quidem? Enim ex quos fugiat ipsam omnis, quae ipsa, illum dolorum iste quibusdam nesciunt ea consequatur, quaerat officia!</p>
        <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolor, consectetur! Velit odit eius incidunt ipsum quo dolores, quas id quisquam enim sunt harum ipsam, a eaque maxime est, fugiat corporis laboriosam inventore aut mollitia adipisci possimus commodi pariatur. Molestiae similique animi adipisci illum!</p>
    </div>
)
